### ISSUE TITLE
Thread blocked when client try auto recovery

### ISSUE THREAD

**Issue by nintha** [vert-x3/vertx-rabbitmq-client#103]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

When network is bad, rabbitmq client recovery will throw exeception: Thread blocked.

### Version

Which version(s) did you encounter this bug ?

vertx-rabbitmq-client 4.0.0-milestone4

### Context

I encountered an exception which looks suspicious while ...
```
WARN [tx-blocked-thread-checker] io.vertx.core.impl.BlockedThreadChecker: Thread Thread[vert.x-worker-thread-5,5,main] has been blocked for 110113 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.1/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base@11.0.1/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base@11.0.1/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base@11.0.1/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base@11.0.1/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base@11.0.1/java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at app//com.rabbitmq.client.impl.SocketFrameHandler.flush(SocketFrameHandler.java:177)
	at app//com.rabbitmq.client.impl.AMQConnection.flush(AMQConnection.java:571)
	at app//com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:134)
	at app//com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:447)
	at app//com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:423)
	at app//com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:704)
	at app//com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:679)
	at app//com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:669)
	at app//com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:192)
	at app//io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$basicPublish$5(RabbitMQClientImpl.java:189)
	at app//io.vertx.rabbitmq.impl.RabbitMQClientImpl$$Lambda$96/0x00000008001b4040.handle(Unknown Source)
	at app//io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$forChannel$24(RabbitMQClientImpl.java:526)
	at app//io.vertx.rabbitmq.impl.RabbitMQClientImpl$$Lambda$92/0x00000008001b6040.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:170)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$81/0x0000000800182c40.handle(Unknown Source)
	at app//io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:183)
	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:168)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$80/0x0000000800183440.run(Unknown Source)
	at app//io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at app//io.vertx.core.impl.TaskQueue$$Lambda$68/0x0000000800144c40.run(Unknown Source)
	at java.base@11.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.1/java.lang.Thread.run(Thread.java:834)
```

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. start rabbitmq client
2. publish lots of texts and consume them
3. let network be high loss by using pumba, 50% loss
4. sometimes it throws Thread blocked Exception, sometimes it print error message about recovery failure

### Extra

* Anything that can be relevant such as OS version, JVM version
Kotlin 1.3.20 jvmTarget = '1.8'
openjdk 11

**Comment by vietj** [comment]
There is nothing wrong with respect to Vert.x as this is using a worker thread. The logging tells us that this is actually consuming a resource (the worker thread) and this is something you don't want to ignore. You can alleviate this using a larger time period for the worker thread to have logging happening less often.
