### ISSUE TITLE
Link between rabbitmq consumer and vertx event bus isnt working when message has headers

### ISSUE THREAD

**Issue by MipH** [vert-x3/vertx-rabbitmq-client#3]
```
// rabbitmq config has "includeProperties": true
RabbitMQClient.create(vertx, config.getJsonObject("rabbitmq"));


// Setup the link between rabbitmq consumer and vertx event bus 
rabbitmq.basicConsume("queue", "amqp.service_channel.message", consumeResult -> {
       // ...
 });
```

When I send AMQP message with AMQP Headers error occures 
```
Unhandled exception
java.lang.IllegalStateException: Illegal type in JsonObject: class com.rabbitmq.client.impl.LongStringHelper$ByteArrayLongString
        at io.vertx.core.json.Json.checkAndCopy(Json.java:115) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.json.JsonObject.copy(JsonObject.java:646) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.json.Json.checkAndCopy(Json.java:94) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.json.JsonObject.copy(JsonObject.java:646) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.json.Json.checkAndCopy(Json.java:94) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.json.JsonObject.copy(JsonObject.java:646) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.eventbus.impl.codecs.JsonObjectMessageCodec.transform(JsonObjectMessageCodec.java:49) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.eventbus.impl.codecs.JsonObjectMessageCodec.transform(JsonObjectMessageCodec.java:27) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.eventbus.impl.MessageImpl.<init>(MessageImpl.java:92) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.eventbus.impl.MessageImpl.copyBeforeReceive(MessageImpl.java:106) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.eventbus.impl.EventBusImpl.doReceive(EventBusImpl.java:748) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.eventbus.impl.EventBusImpl.receiveMessage(EventBusImpl.java:713) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.eventbus.impl.EventBusImpl.sendOrPub(EventBusImpl.java:544) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:149) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:134) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$null$0(RabbitMQClientImpl.java:53) ~[vertx-rabbitmq-client-3.0.0.jar:na]
        at io.vertx.rabbitmq.impl.RabbitMQClientImpl$$Lambda$75/1185211598.handle(Unknown Source) ~[na:na]
        at io.vertx.rabbitmq.impl.ConsumerHandler.lambda$handleDelivery$18(ConsumerHandler.java:55) ~[vertx-rabbitmq-client-3.0.0.jar:na]
        at io.vertx.rabbitmq.impl.ConsumerHandler$$Lambda$120/1066768999.handle(Unknown Source) ~[na:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:314) ~[vertx-core-3.0.0.jar:na]
        at io.vertx.core.impl.ContextImpl$$Lambda$14/1499867659.run(Unknown Source) [vertx-core-3.0.0.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357) [netty-common-4.0.28.Final.jar:4.0.28.Fina
l]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [netty-common-4.0.28.Final.jar:4.0.28.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by eboukamza** [comment]
Hi @MipH ,
I have no issue when I try to consume a message with AMQP Headers.

however your problem seems be caused by the type of contained in the header, which wasn't handled by vertx eventBus, in your case ByteArrayLongString.

You can solve the problem if you provide Vert.x a Codec for decode your object 

see http://vertx.io/docs/vertx-core/java/#_the_event_bus_api

Message Codecs

    eventBus.registerDefaultCodec(MyPOJO.class, myCodec);
    

In any case I think this issue isn't caused by the plugin.

**Comment by kascakm** [comment]
I get the same error. com.rabbitmq.client.impl.LongStringHelper$ByteArrayLongString is produced e.g. when you generate the message via RabbitMQ admin UI.

I'm under the impression that converting should be handled before passing the message to eventbus (ConsumerHandler#handleDelivery). The plugin is responsible for generating valid JsonObject (which does not recognize rabbit's LongString value)

**Comment by poiuytrez** [comment]
Could you send a reproducer?

**Comment by kascakm** [comment]
It's actually same this as https://github.com/vert-x3/vertx-rabbitmq-client/issues/30

Just bind to a queue and from rabbitmq admin publish a message

![rabbitui-publish](https://cloud.githubusercontent.com/assets/12966180/26626956/15c318be-45f9-11e7-9445-e319bc851308.png)

We are using RabbitMQ 3.3.5

**Comment by ThibaultDataberries** [comment]
I can reproduce this issue, i will dig into it soon

**Comment by m1schka** [comment]
is there an update on this? I have exactly the same problem

**Comment by Sammers21** [comment]
@m1schka, using the new consumer API introduced in the 3.6.0 hope you will not have such a problem. Can you try and share your feedback?

@vietj, do we also need to reopen this?

**Comment by m1schka** [comment]
I described my problem in #30 so I guess there is no need to reopen this
