### ISSUE TITLE
basicConsume handler fails on invalid json message

### ISSUE THREAD

**Issue by MipH** [vert-x3/vertx-rabbitmq-client#4]
```
rabbitmq.basicConsume("queue", "amqp.service_channel.message", consumeResult -> { 
// ... 
});
```

Consumer handler will thrown an exception and terminated in case of invalid json message from AMQP
```
DefaultExceptionHandler: Consumer io.vertx.rabbitmq.impl.ConsumerHandler@5918b2f4 (amq.ctag-Yj0RjwWdb2Zg6_pZN4hIPw) method handleDelivery for channel AMQChannel(amqp://guest@127.0.0.1:5672/,1) threw an exception for channel AMQChannel(amqp://guest@127.0.0.1:5672/,1):
io.vertx.core.json.DecodeException: Failed to decode:Unexpected character ('t' (code 116)): was expecting double-quote to start field name
at [Source:
Unknown macro: {type}
; line: 1, column: 3]
at io.vertx.core.json.Json.decodeValue(Json.java:76)
at io.vertx.core.json.JsonObject.fromJson(JsonObject.java:796)
at io.vertx.core.json.JsonObject.<init>(JsonObject.java:47)
at io.vertx.rabbitmq.impl.Utils.parse(Utils.java:101)
at io.vertx.rabbitmq.impl.ConsumerHandler.handleDelivery(ConsumerHandler.java:53)
at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:95)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by poiuytrez** [comment]
Could you send me a reproducer?
