### ISSUE TITLE
SSL option for client

### ISSUE THREAD

**Issue by lanmarti** [vert-x3/vertx-rabbitmq-client#69]
I cannot find any option to turn on SSL, am I simply overlooking this option or is it simply not available?

**Comment by vietj** [comment]
I don't think we support SSL, perhaps you can contribute it ?

**Comment by lanmarti** [comment]
I'll try and look into it later. I know very little about SSL so it might take a while though.

**Comment by vietj** [comment]
it seems it's only a matter of writing a test for it and configure SSL via the wrapped rabbit mq client

**Comment by lanmarti** [comment]
I'm having some problems with the pre-existing tests. I strongly based my test class on the ones already present, but one of the original tests seems to be failing. I'm not sure if this is a problem on my end or not, so I could use some input. The failing test is testReconnect of RabbitMQClientReconnectTest, with the following output: 
`Attempting to reconnect to rabbitmq... 
Could not connect to rabbitmq 
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1004)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:956)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:914)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1068)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.newConnection(RabbitMQClientImpl.java:89)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.connect(RabbitMQClientImpl.java:445)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$23(RabbitMQClientImpl.java:375)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:265)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)`

My own testConnectionWithSsl test seems to have the exact same error, so I feel the issues might be linked.
Current version can be found at https://github.com/lanmarti/vertx-rabbitmq-client but if you prefer I can already make a pull request for it.

**Comment by EddyPan** [comment]
Look forward to supporting SSL.

**Comment by greatbadness** [comment]
Anybody still interested in this feature? I could give it a go perhaps.

**Comment by vietj** [comment]
@greatbadness if you can contribute it's great

**Comment by greatbadness** [comment]
Have raised a PR but the tests are failing because the necessary test/resources (certs and keys) were apparently discarded by github .

**Comment by vietj** [comment]
thanks @greatbadness
